# Generated by Django 3.2 on 2022-05-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtgen', '0004_srtgen_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='srtgen',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
